packages:
  - "apps/**"
  - "!apps/backend/.medusa/**"

allowBuilds:
  '@medusajs/telemetry': true
  '@swc/core': true
  esbuild: true
  msgpackr-extract: true
  protobufjs: true
  sharp: false
  unrs-resolver: false

minimumReleaseAge: 0

overrides:
  "@types/react": "19.0.5"
  "@types/react-dom": "19.0.5"
